version: '3'

networks:
  nestjs-api:
    driver: bridge

services:
  postgres:
    networks:
      - nestjs-api
    container_name: postgres
    image: postgres:16.1
    restart: always
    env_file:
      - .env.local
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./query/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    networks:
      - nestjs-api
    container_name: app
    build:
      context: . # コンテキストを指定
      dockerfile: ./Dockerfile.dev # Dockerfile.devを指定
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app # ソースコードをコンテナにマウント
    env_file:
      - .env.local
    restart: always

volumes:
  postgres_data:
